export enum ROUTES {
  HOME = '/',
  SIGN_IN = '/sign-in',
  SIGN_UP = '/sign-up',
  DASHBOARD = '/dashboard',
  DASHBOARD_BRANCHES = '/dashboard/branches',
  DASHBOARD_CATEGORIES = '/dashboard/categories',
  DASHBOARD_PRODUCTS = '/dashboard/products',
  DASHBOARD_SERVICES = '/dashboard/services',
  DASHBOARD_PRICING = '/dashboard/pricing',
  DASHBOARD_ORDERS = '/dashboard/orders',
  DASHBOARD_ANALYTICS = '/dashboard/analytics',
  BILLING = '/billing',
  BILLING_NEW = '/billing/new',
  BILLING_ORDER_HISTORY = '/billing/history',
  BILLING_TODAY = '/billing/today-schedule',
  BILLING_SETTINGS = '/billing/settings',
  BILLING_ANALYTICS = '/billing/analytics',
  TODAY_SCHEDULE = '/billing/today-schedule',
}
